[global]
        workgroup = SAMBA
        security = user
        passdb backend = tdbsam
        printing = cups
        printcap name = cups
        load printers = yes
        cups options = raw
        include = /etc/samba/usershares.conf
        follow symlinks = yes
        wide links = yes
        allow insecure wide links = yes

[homes]
        comment = Home Directories
        valid users = %S, %D%w%S
        browseable = No
        read only = No
        inherit acls = Yes

[homepc]
        comment = HomePC Directory
        path = /var/home/homepc
        valid users = homepc
        browsable = yes
        writable = yes
        read only = no

[printers]
        comment = All Printers
        path = /var/tmp
        printable = Yes
        create mask = 0600
        browseable = No

[print$]
        comment = Printer Drivers
        path = /var/lib/samba/drivers
        write list = printadmin root
        force group = printadmin
        create mask = 0664
        directory mask = 0775

[WindowsHDD]
        path = /var/mnt/windowshdd
        browsable = yes
        writable = yes
        guest ok = no
        read only = no
        create mask = 0755

[gamedata]
        path = /var/mnt/gamedata
        browsable = yes
        writable = yes
        guest ok = no
        read only = no
